import LeadershipProfileDialog from "./leadership-profile-dialog"
import { leadershipClosingStatement, leadershipModel, leadershipOverview, leadershipProfiles } from "@/constants/leadership"

export default function LeadershipSection() {
    return (
        <section className="w-contain space-y-14 py-15" aria-labelledby="leadership-title">
            <div className="mx-auto max-w-4xl space-y-5 text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#d4af37]">Our Team</p><h2 id="leadership-title" className="text-3xl lg:text-5xl">Meet Our Leadership Team</h2><h3 className="text-lg text-[#d4af37] lg:text-2xl">Leadership driven by design excellence and construction expertise.</h3><div className="space-y-3 text-sm leading-relaxed lg:text-lg">{leadershipOverview.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div>
            <div className="space-y-6"><h3 className="text-2xl lg:text-3xl">Leadership Model</h3><div className="hidden overflow-hidden rounded-2xl border border-white/15 md:block"><table className="w-full table-fixed text-left"><thead className="bg-primary"><tr><th className="w-1/3 p-5">Leadership Team</th><th className="w-1/5 p-5">Role</th><th className="p-5">Industry Skills &amp; Function</th></tr></thead><tbody>{leadershipModel.map((item) => <tr key={item.name} className="border-t border-white/15 align-top"><th scope="row" className="p-5 text-sm font-semibold">{item.name}</th><td className="p-5 text-sm">{item.role}</td><td className="p-5 text-sm leading-relaxed">{item.skills}</td></tr>)}</tbody></table></div><div className="grid gap-4 md:hidden">{leadershipModel.map((item) => <article key={item.name} className="rounded-2xl bg-primary p-5 shadow-lg"><h4 className="text-base">{item.name}</h4><p className="mt-2 text-sm font-semibold text-[#d4af37]">{item.role}</p><p className="mt-3 text-sm leading-relaxed">{item.skills}</p></article>)}</div></div>
            <div className="space-y-6"><h3 className="text-2xl lg:text-3xl">Executive Leadership</h3><div className="grid gap-6 md:grid-cols-2">{leadershipProfiles.map((profile) => <article key={profile.name} className="group flex flex-col overflow-hidden rounded-2xl bg-white p-6 text-[#171717] shadow-lg transition-transform duration-300 hover:-translate-y-1 lg:p-8"><h4 className="text-xl text-primary lg:text-2xl">{profile.name}</h4><p className="mt-3 font-semibold text-[#8a6713]">{profile.role}</p><p className="mt-3 flex-1 text-sm leading-relaxed lg:text-base">{profile.summary}</p><div className="mt-3"><LeadershipProfileDialog profile={profile} /></div></article>)}</div></div>
            <p className="rounded-2xl bg-primary px-6 py-8 text-center font-michroma text-xl leading-relaxed text-white lg:text-3xl">{leadershipClosingStatement}</p>
        </section>
    )
}
